// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1LgEEn3vmgwgVQ9Rmtvz8J5DlSfKFHDc',
    appId: '1:993251629138:web:6944d8f7027dca670e678b',
    messagingSenderId: '993251629138',
    projectId: 'giangtest-2fc07',
    authDomain: 'giangtest-2fc07.firebaseapp.com',
    databaseURL: 'https://giangtest-2fc07.firebaseio.com',
    storageBucket: 'giangtest-2fc07.appspot.com',
    measurementId: 'G-289HQNWWLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjmVDaMSkbdvdu04aMUHbkOYxMmT5z2nk',
    appId: '1:993251629138:android:68041a842559981e0e678b',
    messagingSenderId: '993251629138',
    projectId: 'giangtest-2fc07',
    databaseURL: 'https://giangtest-2fc07.firebaseio.com',
    storageBucket: 'giangtest-2fc07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKhOh1QgRpDiN7Jmd8SrbVmwXoQ6CoDJ8',
    appId: '1:993251629138:ios:ec6490ef8b77a6500e678b',
    messagingSenderId: '993251629138',
    projectId: 'giangtest-2fc07',
    databaseURL: 'https://giangtest-2fc07.firebaseio.com',
    storageBucket: 'giangtest-2fc07.appspot.com',
    iosClientId: '993251629138-ikbnvkv9mj4al9cn9pnksjilha0cjfdf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFlexWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKhOh1QgRpDiN7Jmd8SrbVmwXoQ6CoDJ8',
    appId: '1:993251629138:ios:2c6fb893036c1d950e678b',
    messagingSenderId: '993251629138',
    projectId: 'giangtest-2fc07',
    databaseURL: 'https://giangtest-2fc07.firebaseio.com',
    storageBucket: 'giangtest-2fc07.appspot.com',
    iosClientId: '993251629138-1h99iphhkqcrlvd056pscp9m44igr9pv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFlexWebsite.RunnerTests',
  );
}
